import React from 'react'
import {Row, Col, Button, CardHeader, Card, Modal, CardBody, Input} from 'reactstrap'
import PropTypes from 'prop-types'

const CodeFormatModal = ({modal, toggle}) => {
  return (
    <Modal isOpen={modal} toggle={toggle} className="mt-lg-5 mx-lg-auto m-5">
      <Card>
        <CardHeader>
          <Row>
            <Col lg={6} xs={6} sm={6} className="text-black">
              Set Default Code Format
            </Col>
            <Col lg={6} xs={6} sm={6} className="text-right my-auto">
              <i
                className="fa fa-times"
                aria-hidden="true"
                style={{cursor: 'pointer'}}
                onClick={toggle}
              />
            </Col>
          </Row>
        </CardHeader>
        <CardBody>
          <Row className="border text-black m-0 p-2">
            <Col lg={1} sm={1} xs={2}>
              <span className="fa-stack fa-lg">
                <i className="fa fas fa-question-circle fa-2x text-warning"></i>
              </span>
            </Col>
            <Col sm={11} lg={11} xs={10}>
              <span>
                Set the default format for codes that are generated from gift card products being
                purchased on orders. The codes will be autogenerated based on the format that you
                specify. You can enter the uppercase A for an alphabetic character, a hashtag for a
                number between 0 and 9, or a dash (-).
              </span>
            </Col>
            <Col lg={12} className="my-auto text-right">
              <span>Features Guide Link</span>
            </Col>
          </Row>
          <Row className="mt-3 text-black">
            <Col className="pt-lg-2" lg={4}>
              <span>Default Code Format</span>
            </Col>
            <Col lg={8}>
              <Input placeholder="AA##-AA##" className="mb-2" />
              <span>Example code: CK24-LF43</span>
            </Col>
          </Row>
          <Row className="mt-2">
            <Col lg={6} xs={6} sm={6} md={6} className="text-left">
              <Button color="warning" onClick={toggle}>
                <i className="fa fa-times-circle-o mr-1" color="info" aria-hidden="true" />
                Close
              </Button>
            </Col>
            <Col lg={6} xs={6} sm={6} md={6} className="text-right">
              <Button color="success">
                <i className="fa fas fa-check-circle-o mr-1" />
                Save
              </Button>
            </Col>
          </Row>
        </CardBody>
      </Card>
    </Modal>
  )
}

CodeFormatModal.propTypes = {
  modal: PropTypes.bool,
  toggle: PropTypes.func,
}

export default CodeFormatModal
