import React, {useContext, useEffect} from 'react'
import {Row, Col, Button, Card, FormGroup, Label, Input, Form} from 'reactstrap'
import {useHistory} from 'react-router-dom'
import Select from 'react-select'
import AppContext from 'components/App/AppContext'

const CreateGiftCard = () => {
  const context = useContext(AppContext)
  const {setTitle} = context

  const history = useHistory()

  useEffect(() => {
    setTitle('Generate Gift Cards')
  }, [])

  const routeChange = () => {
    history.push('/products/gift-card-manager')
  }

  const countryOptions = [
    {
      label: 'United States',
      value: 1,
    },
  ]

  return (
    <Row className="mt-3 m-2">
      <Card lg={12} md={12} sm={12} xs={12} className="mb-3 text-white rounded-top p-3">
        <Row className="border text-black m-0 p-2">
          <Col className="col-md-auto">
            <span className="fa-stack fa-lg">
              <i className="fa fas fa-question-circle fa-2x text-warning" />
            </span>
          </Col>
          <Col sm={11} lg={11} xs={10} className="pl-lg-0">
            <span>
              Here you can generate 1 or many new gift card codes in the format, value, and currency
              that you would like. The codes will be autogenerated based on the format that you
              specify. You can enter the uppercase A for an alphabetic character, a hashtag for a
              number between 0 and 9, or a dash (-).
            </span>
          </Col>
          <Col lg={12} className="my-auto text-right">
            <span>Features Guide Link</span>
          </Col>
        </Row>
        <Form className="mt-3">
          <FormGroup row>
            <Label for="code" sm={3} className="text-dark text-lg-right">
              Gift Card Code Format
            </Label>
            <Col sm={4}>
              <Input type="text" id="code" placeholder="AA##-A#A#" />
            </Col>
          </FormGroup>
          <FormGroup row>
            <Label for="number" sm={3} className="text-dark text-lg-right">
              Number of codes to generate
            </Label>
            <Col sm={2}>
              <Input type="number" id="number" />
            </Col>
          </FormGroup>
          <FormGroup row>
            <Label for="value" sm={3} className="text-dark text-lg-right">
              Gift Card Value
            </Label>
            <Col sm={2} className="mb-2 mb-lg-0">
              <Input type="text" id="value" placeholder="10.00" />
            </Col>
            <Col sm={2}>
              <Select options={countryOptions} />
            </Col>
          </FormGroup>
        </Form>
      </Card>
      <Col xs={6} lg={6} className="pl-0">
        <Button color="danger" onClick={routeChange}>
          Cancel
        </Button>
      </Col>
      <Col xs={6} lg={6} className="text-right pr-0">
        <Button color="spotify" onClick={routeChange}>
          Generate Codes
        </Button>
      </Col>
    </Row>
  )
}

export default CreateGiftCard
